language: node_js

node_js:
  - '5'

before_install:
  - gem install sass
  - gem install compass
  - npm install -g grunt-cli
  - npm install -g bower

install:
  - npm install
  - bower install

script: grunt

deploy:
  provider: s3
  access_key_id: AKIAIY6GS62P3XUFWMPA
  secret_access_key:
    secure: "mAnoc9K2Xd1vQ+NSJ267mr26SFyAFlP+6O43OY4B/B6Q7QZaincy5PdjSH9nU4jUTTdgDevqaXOWcr1IDhFrmpDcCl4yDlcJu8q902uSz2UTUEV7GQgV+1qw+YLODjeBYD2JsRTpy9awURHKxSX+6ultB6z4I4gk9sOkMYqkgsA="
  bucket: www.shouldiorderapizza.com
  region: us-east-1
  local_dir: dist
  skip_cleanup: true
  acl: public_read
