language: node_js

node_js:
  - '5'

before_install:
  - gem install sass
  - gem install compass
  - npm install -g grunt-cli
  - npm install -g bower

install:
  - npm install
  - bower install

script: grunt --force

deploy:
  provider: s3
  access_key_id: AKIATTEYYVIMBB3Y6ZFO
  secret_access_key:
    secure: "OdwlfcfNRShr/jxuqwsxt+rO/Gzpo+KMce6zNpwZsS0Y9thZn6JBLvGQOI+34xKXTm/v5fgckvpzZ11QpMD4JKjsdMRUIWo/tetn4MMUjmSCAM4vHJM8XrZb+P5dDikNn6ly1CYaGlQU5XEVN0LEhDjXiFYwxrQVFtK3BIvzdNk="
  bucket: www.shouldiorderapizza.com
  region: us-east-1
  local_dir: dist
  skip_cleanup: true
  acl: public_read
  cache_control: max-age=0
