language: node_js

node_js:
  - '0.10'

before_install:
  - gem install sass
  - gem install compass
  - npm install -g grunt-cli
  - npm install -g bower

install:
  - npm install
  - bower install

before_script:
  - grunt build

deploy:
  provider: s3
  access_key_id: AKIAI2DPVV36N4UIUWLQ
  secret_access_key:
    secure: FcZwaiyFJpfCAe3MHhC7zcjz3pviIfTmpRpzuJNQ8MOjSb+P+iNUEGJASIDctt81IrnO7m8GtuTfOXV96MeROLvG/PDwb/s4feceBRZMQlT8Mk8lddvUfttgP3cCC5vD4LzzM0cZKOS2gWz/eS+53yjM+Cov59UhsJenl/fDvHU=
  bucket: www.shouldiorderapizza.com
  endpoint: www.shouldiorderapizza.com.s3-website-us-east-1.amazonaws.com
  local_dir: dist
  acl: public_read
  on:
    repo: Sinetheta/shouldiorderapizza
