language: node_js

node_js:
  - '5'

before_install:
  - gem install sass
  - gem install compass
  - npm install -g grunt-cli
  - npm install -g bower

install:
  - npm install
  - bower install

script: grunt

deploy:
  provider: s3
  access_key_id: AKIAI2DPVV36N4UIUWLQ
  secret_access_key:
    secure: FcZwaiyFJpfCAe3MHhC7zcjz3pviIfTmpRpzuJNQ8MOjSb+P+iNUEGJASIDctt81IrnO7m8GtuTfOXV96MeROLvG/PDwb/s4feceBRZMQlT8Mk8lddvUfttgP3cCC5vD4LzzM0cZKOS2gWz/eS+53yjM+Cov59UhsJenl/fDvHU=
  bucket: www.shouldiorderapizza.com
  region: us-east-1
  local_dir: dist
  skip_cleanup: true
  acl: public_read
